"""initial migration

Revision ID: 4d26ee409f4e
Revises: 
Create Date: 2025-07-03 09:01:22.978667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d26ee409f4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_status'), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('town', sa.String(length=50), nullable=True),
    sa.Column('registration_level', sa.Enum('basic', 'details', 'completed', name='registration_stage'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('match_requests',
    sa.Column('match_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age_range_start', sa.Integer(), nullable=True),
    sa.Column('age_range_end', sa.Integer(), nullable=True),
    sa.Column('town', sa.String(length=50), nullable=True),
    sa.Column('total_matches', sa.Integer(), nullable=True),
    sa.Column('current_offset', sa.Integer(), nullable=True),
    sa.Column('matches_per_page', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_match_requests_user_id_users')),
    sa.PrimaryKeyConstraint('match_request_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_messages_recipient_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('profession', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.Enum('single', 'married', 'divorced', name='marital_status_enum'), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('self_description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_details_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profile_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_request_id', sa.Integer(), nullable=False),
    sa.Column('matched_user_id', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_request_id'], ['match_requests.match_request_id'], name=op.f('fk_profile_match_match_request_id_match_requests')),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], name=op.f('fk_profile_match_matched_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_match')
    op.drop_table('user_details')
    op.drop_table('messages')
    op.drop_table('match_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
